openapi: "3.0.0"
info:
  version: 1.0.0
  title: Revolut for Business OpenAPI
servers:
  - url: https://b2b.revolut.com/api/1.0
  - url: https://sandbox-b2b.revolut.com/api/1.0
paths:
  /webhook:
    get:
      summary: Get an existing webhook
      operationId: getWebhook
      security:
        - AccessToken: [read]
      tags:
        - webhooks
      responses:
        '200':
          description: An existing webhook
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Webhook"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Set up a webhook
      operationId: setupWebhook
      security:
        - AccessToken: [write]
      tags:
        - webhooks
      requestBody:
        description: URL to set up as a webhook
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Webhook"
      responses:
        '204':
          description: Webhook has been set up
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete a webhook
      operationId: deleteWebhook
      security:
        - AccessToken: [write]
      tags:
        - webhooks
      responses:
        '204':
          description: Webhook has been deleted
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    AccessToken:
      type: http
      scheme: bearer
  schemas:
    Webhook:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          format: uri
    Error:
      type: object
      required:
        - message
        - code
      properties:
        code:
          type: integer
        message:
          type: string
